### ISSUE TITLE
import { Pool } from "pg"; Error

### ISSUE THREAD

**Issue by not-amplify** [titaniumnetwork-dev/serverguard#4]
hi i keep getting this error and i dont know what to edit to fix it: 
![image](https://github.com/titaniumnetwork-dev/serverguard/assets/155575594/18d624b5-c953-4697-a234-d54869224a7d)

**Comment by Notplayingallday383** [comment]
you need to be using bun

**Comment by not-amplify** [comment]
> you need to be using bun

How would I install it?

**Comment by Rein1n** [comment]
`curl -fsSL https://bun.sh/install | bash`

**Comment by Rein1n** [comment]
Also for future reference, please copy and paste errors rather than screenshot, makes it easier to reference the internet.
